name: MiniGamePl
version: 1.0
author: PalaPika
main: fr.palapika.minigame.MiniGame
api-version: 1.16
commands:
  joingame:
    description: Permet au joueur de rejoindre le jeu si il n'est pas en cours
    usage: /command
    aliases: join
  start:
    description: Permet de lancer le jeu
    usage: /command
    aliases: joingame
  colorgameinit:
    description: Permet d'initialiser colorGame
    usage: /command
    permission: minigame.colorgameinit
  circle:
    description: Permet de creer un cercle de block sous le joueur cible
    usage: /command
  broadcast:
    description: Permet de ...
    usage: /command
  territory:
    description: Permet de ...
    usage: /command